import Head from "next/head";
import HompageIntro from "@/components/homepage/homepage-intro";
import HomepageSelectTests from "@/components/homepage/homepage-select-test";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HompageIntro />
        <HomepageSelectTests />
      </main>
    </>
  );
}
